project_id = "rgfabywkwllxoqsahrpt"

[functions.api-gateway]
verify_jwt = false

[functions.send-email-digest]
verify_jwt = false

[functions.send-test-email]
verify_jwt = true

[functions.send-portfolio-review-email]
verify_jwt = false
